### ISSUE TITLE
Setup sans docker!

### ISSUE THREAD

**Issue by falun** [dustball/gping.io#12]
At one point we had a guide to run this without docker in the mix -- that is still valuable and needs docs added back as an alternative

**Comment by finid** [comment]
I'll like to run a production setup, but [this guide](https://github.com/dustball/gping.io/blob/master/docs/Production.md) needs love.

**Comment by falun** [comment]
@finid I filed https://github.com/dustball/gping.io/issues/15; add a comment and let us know what the environment you want to run under. We'll add docs on how to set up with your use case in mind and use that as a starting point for the `run in production` docs.
